controller_manager:
  ros__parameters:
    update_rate: 1000
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controllers:
      type: effort_controllers/JointGroupEffortController

effort_controllers:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
      
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

    state_publish_rate: 1000.0
    action_monitor_rate: 1000.0